# Form implementation generated from reading ui file 'eazy_editor.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 602)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.files_list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.files_list.setGeometry(QtCore.QRect(10, 50, 221, 501))
        self.files_list.setObjectName("files_list")
        self.dir_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.dir_btn.setGeometry(QtCore.QRect(30, 10, 151, 31))
        self.dir_btn.setObjectName("dir_btn")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(240, 480, 441, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_btn_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.left_btn_2.setObjectName("left_btn_2")
        self.horizontalLayout.addWidget(self.left_btn_2)
        self.right_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.right_btn.setObjectName("right_btn")
        self.horizontalLayout.addWidget(self.right_btn)
        self.mirror_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.mirror_btn.setObjectName("mirror_btn")
        self.horizontalLayout.addWidget(self.mirror_btn)
        self.sharp_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.sharp_btn.setObjectName("sharp_btn")
        self.horizontalLayout.addWidget(self.sharp_btn)
        self.bw_btn = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.bw_btn.setObjectName("bw_btn")
        self.horizontalLayout.addWidget(self.bw_btn)
        self.photo_lb = QtWidgets.QLabel(parent=self.centralwidget)
        self.photo_lb.setGeometry(QtCore.QRect(240, 10, 541, 451))
        self.photo_lb.setObjectName("photo_lb")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dir_btn.setText(_translate("MainWindow", "Папка"))
        self.left_btn_2.setText(_translate("MainWindow", "Вліво"))
        self.right_btn.setText(_translate("MainWindow", "Впараво"))
        self.mirror_btn.setText(_translate("MainWindow", "Дзеркально"))
        self.sharp_btn.setText(_translate("MainWindow", "Різкість"))
        self.bw_btn.setText(_translate("MainWindow", "Чорнобіло"))
        self.photo_lb.setText(_translate("MainWindow", "картинка"))
